name = "edc_client"
description = "Client library for: github.com/hgrodriguez/embedded-dashboard-console"
version = "1.3.3"
licenses = "BSD-3-Clause"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]
tags = ["embedded", "rp2040"]
website = "https://github.com/hgrodriguez/edc-client"

[[depends-on]]  # Added by alr
hal = "~0.1.0"  # Added by alr
