name = "edc_client"
description = "Client library for: github.com/hgrodriguez/embedded-dashboard-console"
version = "0.0.1"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]
[[depends-on]]  # Added by alr
hal = "~0.1.0"  # Added by alr
